# Rule descriptions:
#
# - https://revive.run/r
# - https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md

ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 1

[rule.add-constant]
[rule.argument-limit]
arguments = [8]
[rule.atomic]
[rule.banned-characters]
[rule.bare-return]
[rule.blank-imports]
[rule.bool-literal-in-expr]
[rule.call-to-gc]
[rule.cognitive-complexity]
[rule.comment-spacings]
[rule.confusing-naming]
[rule.confusing-results]
[rule.constant-logical-expr]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.cyclomatic]
[rule.datarace]
[rule.deep-exit]
[rule.defer]
[rule.dot-imports]
[rule.duplicated-imports]
[rule.early-return]
[rule.empty-block]
[rule.empty-lines]
[rule.enforce-map-style]
[rule.enforce-slice-style]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.errorf]
[rule.exported]
Disabled = true
[rule.file-header]
[rule.flag-parameter]
[rule.function-length]
[rule.function-result-limit]
arguments = [6]
[rule.get-return]
[rule.identical-branches]
[rule.if-return]
[rule.import-alias-naming]
[rule.import-shadowing]
[rule.imports-blocklist]
[rule.increment-decrement]
[rule.indent-error-flow]
[rule.line-length-limit]
arguments = [80]
[rule.max-control-nesting]
[rule.max-public-structs]
Disabled = true
[rule.modifies-parameter]
[rule.modifies-value-receiver]
[rule.nested-structs]
[rule.optimize-operands-order]
[rule.package-comments]
Disabled = true
[rule.range-val-address]
[rule.range-val-in-closure]
[rule.range]
[rule.receiver-naming]
[rule.redefines-builtin-id]
[rule.redundant-import-alias]
[rule.string-format]
[rule.string-of-int]
[rule.struct-tag]
[rule.superfluous-else]
[rule.time-equal]
[rule.time-naming]
[rule.unchecked-type-assertion]
[rule.unconditional-recursion]
[rule.unexported-naming]
[rule.unexported-return]
[rule.unhandled-error]
[rule.unnecessary-stmt]
[rule.unreachable-code]
[rule.unused-parameter]
[rule.unused-receiver]
[rule.use-any]
[rule.useless-break]
[rule.var-declaration]
[rule.var-naming]
[rule.waitgroup-by-value]
